flags:
    text:
        integer-simple: False
packages:
- '.'
extra-deps:
- parsec-3.1.9
- mtl-2.2.1
- text-1.2.1.3
- hspec-2.1.10
- HUnit-1.2.5.2
- QuickCheck-2.8.1
- hspec-core-2.1.10
- hspec-discover-2.1.10
- hspec-expectations-0.7.1
- ansi-terminal-0.6.2.2
- async-2.0.2
- quickcheck-io-0.1.1
- random-1.1
- setenv-0.1.1.3
- tf-random-0.5
- primitive-0.6
- stm-2.4.4
- llvm-general-3.4.5.4
resolver: ghc-7.10
